### ISSUE TITLE
GUI overflows when horizontal resolution under 768

### ISSUE THREAD

**Issue by MrMormon** [Blackvoxel/Blackvoxel#2]
Easy to replicate. :) Text and selectors don't resize that small.

**Comment by Blackvoxel** [comment]
Thanks for your report.
By design, Blackvoxel is designed to work with a minimum screen resolution of 1024x600.
In order to keep crisp text and undeformed images, Blackvoxel GUI doesn't use scalling.
Support for HIDPI laptop screens is planned for the future, so we'll add an optionnal scalling option for the GUI.
Not sure how it could help with very low resolution screen. It will prevent overflow but the text might become unreadable.
Very low resolution screen such as mobile device would need to design specific GUI.
The Blackvoxel Team

**Comment by 0joshuaolson1** [comment]
The list of available resolutions still includes several options that make the window too narrow (when not in fullscreen) to see some text, but more importantly too narrow to change it back without messing with `Settings_Hardware.dat`.
