### ISSUE TITLE
I’m stuck!

### ISSUE THREAD

**Issue by tYYGH** [Blackvoxel/Blackvoxel#27]
First, I want to thank the Blackvoxel team for this wonderful game! I love it and spent (too many) hours until I got my all-automated factory of everything, fed by my automated mining&sorting robot :-)

But I can’t play any more: my “feet” are stuck in the ground… It already happened to me, but so far I only had to dig a couple of voxels around my feet, and as soon as I dropped 1 step in the Y direction, I was free.

Not this time :-( I am literally buried alive a dozen voxels below my initial position, and still I can only jump, but not move in either of the 4 directions…
Help me! Is there a way I can suicide, so that I can re-spawn at 0,0,0?

**Comment by Blackvoxel** [comment]
Hi tYYGH,

Thanks for your interest in Blackvoxel. We are happy to hear you like our game.

We are very sorry for this issue. This happens very rarely, but unfortunately, it happens...

There is two way to get out of this.

(1) Press the "Delete" key (not backspace) in order to "suicide" without losing your inventory. This key can be called otherwise in non english countries. It is the key bellow "insert" and to the left of "end".

Or...

(2) Delete the "PlayerInfo.dat" in the universe directory. You must get out of the game first. This will reset you player, but also your inventory.

In the hope we have helped you.

The Blackvoxel Team
