### ISSUE TITLE
[feature request] robots stop working when far from the player; could that be changed?

### ISSUE THREAD

**Issue by tYYGH** [Blackvoxel/Blackvoxel#30]
Concerned that I may eventually exhaust the resources of the Central Blue Flat Zone (CBFZ), I decided to probe the underground of the blue zone that lays between the 3D Caves, and the Mathematical Structures. I won’t spoil other players about the result, but…

I left my programmable robot #99 on its own, took my plane and went back to tend to my factory at the CBFZ. There and then, I noticed at the console, the line “`Robot 102 restored.`”, which is output by my program when one of my robots is serialized back into working state from its on-disk state-file.

Surprised, I took my plane again and went back beyond the 3D Caves. Sure enough, I saw the line “`Robot 99 restored.`” appear!

I conclude, that robots stop working when the boss is away :-p

While I understand, that it is impossible to make the whole world “live” at each time-tick, and also impossible to do so around _all_ dynamic voxels (there are too many of these), would it be possible to have a “bubble” of living-world at least around programmable robots?
Programmable robots are a special case, because building them requires technology and materials, that only become available after the player has travelled, …

⚠ _spoiler alert_ ⚠

… and when the player has begun to understand the importance of finding a good number of Iron, Copper, and X-Material voxels.
Thus it seems logical to me, that players would try what I just did: set robots to dig at other places.

What do you think?

**Comment by tYYGH** [comment]
Related topic… I wrote above about distance in the X and Z axis. The Y axis (underground) _seems_ to behave a bit differently:

I have a robot digging again and again right next to my factory (and to me), and it reached the grey layer. I expect it to reach the pink layer very soon.

While the robot is “enabled”, it does not seem to ever stop, even when far underground. Hovewer, when it is at the bottom of the pit when I launch the game, I have to descend myself far below until I see the expected “`Robot 82 restored.`” line. Then I can go back up. Thankfully, I programmed my robot to carve step for me all around the pit ;-)

Well, in short, distance in the Y axis seems to be _a bit_ less of a problem, than it is in the X and Z axis.

**Comment by Blackvoxel** [comment]
Hi tYYGH,

Yes, the robot and all automations are unloaded when you goes away from it.

Technically it would be completely impossible to make the whole world active at the same time because the needed cpu power would be over the capacity of the best supercalculator in the world.

The size of the live zone around the player can be configured in the settings. But you'll quickly find the limit at increasing it, even if you have a very powerful computer.

When making the game, we have thinked about making a portion of active world around a robot. But we decided not to do so for several reasons.

First, a limited active zone around robot would unfortunately do nasty side effects. In Blackvoxel, a lot of voxels are active and would behave in a weird and unnatural way in a very limited space. You can expect also a lot of problems with some automations. This would bring too much problems to worth it. Another idea would be to make a larger portion of world active around robot would work much better. But will require too much cpu power for many machines.

Beyond technical problems, there is questions on weither it would be good or bad for gameplay. Depending on the point of view, a limitation can be a bad thing or a good thing. In Blackvoxel, we decided that things would be strongly focused on making things in the area where the player is. This is giving value for two paradigms : traveling and period of stay. Because resources and control in far locations aren't accessible and they remains "off" when player isn't here, this encourage the player to develop planification and organisation. And that's what Blackvoxel game is about.

About how we make choices of features to implement : we are working on this game since 8 years. This also implies we also thinked a very long time about and already have explored a lot of ideas, a lot of ways. We have a lot of ideas waiting to be implemented. But of course, we have to make choices for programming time, gameplay direction as well as artistic preferences

A note about feature suggestions, we prefer that these kind of discussion to be on our forum (in the suggestion section http://forum.blackvoxel.com/index.php?board=2.0) in order to keep this bug section on github dedicated only for bugs. But also to keep related discussions in one place. You'll also find in the forum a lot of other suggestions some players had done and discussions about it.

Thanks for submiting your toughts.

The Blackvoxel Team

**Comment by tYYGH** [comment]
Thank you Blackvoxel Team for this detailed answer! I perfectly understand your reasoning and your choices. And as you say, this leads to gameplay consequences, which I find perfectly acceptable. For example, I noticed, that my channel bringing water from the “sea” to underneath my factory near 0,0,0 would always dry-up eventually because the sea is too far away. This forced me to eventually build the better plane, to go and get water generators :-)
It would be nice if there was a narrative explanation for this phenomenon, just like there is an explanation for not drowning in water (space suit).

I did not know about the forums, but now I do. Nice.
