### ISSUE TITLE
Pixel artifacts around text letters

### ISSUE THREAD

**Issue by GithubSuckBigTime** [Blackvoxel/Blackvoxel#32]
There are small pixel artifacts around some letters, I've noticed it mostly around "T". You can see them e.g. when hovering over the RTFM block. In this picture some of them are indicated by the red arrows:

![image](https://user-images.githubusercontent.com/46821359/51399475-5a68f780-1b46-11e9-93cd-796110c7a7a2.png)

**Comment by Blackvoxel** [comment]
Hello GithubSuckBigTime,

Thanks for submitting your issue.

We can say that this is not a common problem.

The render engine of Blackvoxel is rather stabilised since a long time and we tried it on a lot of hardware.

We didn't see any issue on various PC and graphic hardware we tried with it. At least with common gaming hardware with AMD/NVIDIA GPU.

However, that can be caused by a buggy GPU driver, a regression triggered by an underlying library or maybe by forcing some uncommon AA/AF modes in graphic settings.

Can you give more informations on the Operating System, the hardware and the Graphic GPU used in your System?

Can you look in your graphic settings to see if any filtering or anti aliasing is applied to the games?

Best Regards,

The Blackvoxel Team

**Comment by GithubSuckBigTime** [comment]
Thank you for your response!

Sadly I have now installed a new GNU/Linux distribution, built the game from source and can not reproduce this anymore, the text is rendered correctly this time.

I am only able to provide this information about the version I ran that had this bug:
- The game version was 2.31 (the same version I have reported [this issue](https://github.com/Blackvoxel/Blackvoxel/issues/31) with). Think I installed it from a Debian package I downloaded from the game site.
- The distro was Linux Mint.
- The GPU was GeForce GTX 760. Unfortunately I am not sure if I was using the proprietary or free driver for it.

So I will leave it up to you to either close this issue, or leave it open in case anyone else experienced this and would be able to provide more info.

**Comment by Blackvoxel** [comment]
Thanks anyway for reporting this problem.

As we suspected, it is likely to be a driver bug.

The information you mentioned may help to reduce the field of investigation.

We'll left this issue open in case someone encounter the same issue and may provide further informations.

Best Regards,

The Blackvoxel Team

**Comment by Blackvoxel** [comment]
Since no one else has reported this bug and we've never encountered it with current hardware, we think it's probably due to a driver rather than our code.
We close.
